### ISSUE TITLE
Can't run Get-BusinessCentralDownloadURL.ps1

### ISSUE THREAD

**Issue by AIGARSJ** [SimonOfHH/D365BCDownloadHelper#1]
Getting this error:
The format of value '[Microsoft.PowerShell.Commands.PSUserAgent]::Chrome' is invalid.
when run your script from PowerShell 7.0.

Any idea why?

**Comment by SimonOfHH** [comment]
Hi @AIGARSJ sorry for not getting back earlier to you. For some reason I didn't get any notification from GitHub for this issue :( I'll look into this and get back to you, ok?

**Comment by SimonOfHH** [comment]
Hi again @AIGARSJ, I was able to reproduce the problem. It looks like with PS 7 (I tested with PS 7.1) it's necessary to explictly use the UserAgent as a String. I modified it (see Commit 1b0778d) and tested afterwards with PS 7.1 and 5.1 - both work fine now.

If you encounter anything else, feel free to open another issue :)
