### ISSUE TITLE
Get-BusinessCentralDownloadURL generate wrong download URL

### ISSUE THREAD

**Issue by AIGARSJ** [SimonOfHH/D365BCDownloadHelper#3]
![image](https://user-images.githubusercontent.com/15418150/100318698-232bc300-2fc7-11eb-8465-f39c807de821.png)
![image](https://user-images.githubusercontent.com/15418150/100318705-258e1d00-2fc7-11eb-9e24-a5a215e93bc9.png)

**Comment by SimonOfHH** [comment]
Thanks for your feedback @AIGARSJ I'll look into this asap

**Comment by SimonOfHH** [comment]
Hi @AIGARSJ, as promised I looked into this. The problem with some older versions is, that they are only available via PartnerSource oder CustomerSource and not via Microsoft Download Center (at least I couldn't find them publicly). Were you able to find them on a public MS site? Or did I just miss something and need another coffee? ;-)

Any input from your side is appreciated :)

**Comment by AIGARSJ** [comment]
I can't find them publicly too. :)

**Comment by SimonOfHH** [comment]
Well, then I have no other option right now than to close this issue unresolved :( 

But anyway: thanks for your input :)
